//const add = require('./add')
//const sub = require('./sub')
//const div = require('./div')
//const mul = require('./mul')
const add1 = require('./calculation')
//console.log(add(10,20))
//console.log(sub(10,20))
//console.log(mul(10,20))
//console.log(div(10,20))

console.log(add1.add(10,20))
console.log(add1.sub(10,20))
console.log(add1.mul(10,20))
console.log(add1.div(10,20))